version: '3.2'
services:
  webserver:
    restart: always
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    ports:
      - '${PORT_WEBSERVER}:80'
      - '${PORT_WEBSOCKET}:6001'
    volumes:
      - ../../.:/app
    environment:
      WEB_DOCUMENT_INDEX: index.php
      VIRTUAL_HOST: '${HOSTNAME}'
      LETSENCRYPT_HOST: '${HOSTNAME}'
      LETSENCRYPT_EMAIL: '${EMAIL}'
    container_name: '${PROJECT_NAME}_web'
    networks:
      - partymeister
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '${PORT_MYSQL}:3306'
    volumes:
      - 'data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    container_name: '${PROJECT_NAME}_db'
    networks:
      - partymeister
volumes:
  data: null
networks:
  partymeister:
    driver: bridge
