version: "3.8"
services:
  app:
    image: zeitraumdev/php8-grpc-laravel:1
    environment:
      APP_NAME: partymeister
      APP_URL: localhost
      DB_HOST: mysql
      DB_CONNECTION: mysql
      DB_PORT: 3306
      DB_DATABASE: partymeister
      DB_USERNAME: user
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PASSWORD: password
      QUEUE_CONNECTION: redis
      REDIS_CLIENT: predis
      REDIS_PORT: 6379
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
      - ./docker-compose/php/custom_php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker-compose/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - partymeister_network
    depends_on:
      - nginx
      - mysql
      - redis

  nginx:
    image: nginx:1.21
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - partymeister_network

  redis:
    image: wodby/redis:6
    environment:
      REDIS_PASSWORD: password
    networks:
      - partymeister_network
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8-oracle
    restart: always
    environment:
      MYSQL_DATABASE: partymeister
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - partymeister_network


volumes:
  mysql:
    external: false
networks:
  partymeister_network:
    driver: bridge
